drop table REGISTRY_DOCUMENTS;
drop table REGISTRY_MCID_DOCUMENTS;

create table REGISTRY_DOCUMENTS (

   REGISTRY_DOCUMENTS_ID INTEGER not null generated always as identity,
   REGISTRY_DOCUMENTS_MCGUID VARCHAR(255),
   REGISTRY_DOCUMENTS_KEY VARCHAR(255),
   REGISTRY_DOCUMENTS_LOCATION VARCHAR(255),
   REGISTRY_DOCUMENTS_TIMESTAMP VARCHAR (255)
);

create table REGISTRY_OWNER_GUID_LINK (
   REGISTRY_OWNER_GUID_LINK_ID INTEGER not null generated always as identity,
   REGISTRY_OWNER_DOCUMENT_GUID  VARCHAR(255),
   REGISTRY_OWNER_DOCUMENT_MCID VARCHAR(255)
);

commit;