<?php
require_once "is.inc.php";

function linewrap ($s)
{
	return "
	$s";
}
function process_simtrak_dd_table($table,$rr)
{

	$bufa='';
	switch ($rr['fieldtype']	)
	{
		case 'G': break;  // type G is a digital signature that does not come in the csv files and hence should not generate tables
		case 'D':
		
			$bufa .= linewrap("  `{$rr['fieldname']}` varchar(10) NOT NULL, -- {$rr['description']} date forced to 10 chars  " ); break;
		case 'M': 
			$bufa .= linewrap("  `{$rr['fieldname']}` varchar(250) NOT NULL, -- {$rr['description']} forced to 250 chars  " ); break;
		case 'C':
	
		case 'L':

		case 'N':
		default:
			$bufa .= linewrap("  `{$rr['fieldname']}` varchar({$rr['length']}) NOT NULL, -- {$rr['description']}   " );
			//die ("unknown fieldtype");

	}
	return $bufa;
}
//main starts here
header("Content-type: text/plain");

$ops = array ('create_schema');//,'create_schema');

$gmt = strftime('%T %D');

$tables=array();//a full platter of tables
$result = dosql("Select distinct ddtable from datadictionary");
while ($r=isdb_fetch_object($result)) $tables[] = $r->ddtable;
mysql_free_result($result);
//do the same thing for each distinct table


foreach ($tables as $table)
{
	$mid='';


	$top = <<<XXX

	--
	--  Table structure for table $table
	--  Generated by MedCommons stschemabuilder @ $gmt

	CREATE TABLE IF NOT EXISTS $table (   `id` int(11) NOT NULL auto_increment,
XXX;
	$first='';
	$result = dosql("Select * from datadictionary where ddtable='$table' ");
	while ($r=isdb_fetch_array($result)){ $mid .= process_simtrak_dd_table($table,$r); if ($first=='') $first = $r['fieldname'];}
	mysql_free_result($result);
	$bottom = <<<XXX
	  `grid` int(11) NOT NULL, PRIMARY KEY  (`id`),
  		KEY `grid` (`grid`)
 ) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;	
XXX;

	echo linewrap($top).$mid.linewrap($bottom);
}


//that's about all

?>