<?php
require_once "is.inc.php";
function linewrap ($s)
{
	return "
	$s";
}
function code($layout)
{
	$code ="
	function make_section_tabs_$layout ()
	{ \$alltabs=\$alljs=\$navsetmid='';
";
	$first=true;
	$result = dosql("Select * from viewerorder where layout='$layout' order by displayorder ");
	while ($r=isdb_fetch_object($result))
	{
		if (!isset($tablesloaded [$r->ddtable])) {
			$code .= "\$_$r->ddtable = load_table('$r->ddtable');
	";	
			$tablesloaded [$r->ddtable]=true;
		}


		//	onesection('$r->label','$r->label-section-markup','$r->tab' );
		if ($r->displaystyle=='vertical')
		$code .= "list (\$m,\$js,\$nav)=onetab_vertical (\$_$r->ddtable,'viewA', '$r->tabkey','$r->ddtable','$r->label','$r->ddtable-$r->label-markup','$r->sortkey','');

		\$alltabs.=\$m; \$alljs.=\$js; \$navsetmid .=\$nav;
";
		else
		$code .= "list (\$m,\$js,\$nav)=onetab_horizontal(\$_$r->ddtable,'viewA','$r->tabkey','$r->ddtable','$r->label','$r->ddtable-$r->label-markup','$r->sortkey','$r->extra','$r->pivotfield');
		\$alltabs.=\$m; \$alljs.=\$js; \$navsetmid .=\$nav;
";
		$first = false;
	}

	mysql_free_result($result);

	$code.='$nav = '."'".'<div id="demo" class="yui-navset">
<ul class="yui-nav">'."'".
		".\$navsetmid."."'".'</ul>  
<div class="yui-content"> '."';"."			
return \$nav.\$alltabs.\$alljs;
}
";

	return linewrap ('/* enumerate tabs for layout $layout  */').linewrap ($code);

}
//main starts here
header("Content-type: application/octet-stream");
header("Content-Disposition: attachment; filename=\"stview.inc.php\"");
$viewers=array('viewA','viewB');
$metadata = array(); // to accumulate json segments

$gmt = strftime('%T %D');
echo "<?php
//
//generated by MedCommons stviewbuilder @ $gmt
//

";
$tables=array();//a full platter of tables



//$result = dosql("Select distinct source from tabparts");

$result = dosql("Select distinct ddtable from viewerorder");
while ($r=mysql_fetch_object($result)) {
	echo linewrap('$tables_[] = "'.$r->ddtable.'";');
}
mysql_free_result($result);


$result = dosql("Select * from viewerorder");
while ($r1=mysql_fetch_object($result)) {
	$tabkey= $r1->tabkey;
	$displaystyle = $r1->displaystyle;
	if ($displaystyle=='horizontal') $tabkey = $r1->ddtable; // if this is a horizontal display, go do table
	else // vertical
		 $sec = array();
	$mid='';
	$top = <<<XXX
	/* fields for tab $tabkey  $displaystyle */
			
XXX;
	$once = true; $lastpane = -1;
	if ($displaystyle=='horizontal')

	$result2 = dosql("Select * from datadictionary where ddtable='$tabkey' "); else

	$result2 = dosql("Select * from datadictionary where tabkey = '$tabkey' order by ddtable,tabkey,pane,line ");

	while ($r=mysql_fetch_array($result2)) {
		$fn=$r['fieldname'];
		
		$mid.=//"		//table {$r['ddtable']} field {$r['fieldname']}		".
		'
		$labels_'."['$tabkey']"."['".$fn."'] = ".'"'.$r['reportwriterheading'].'";  '; 
		$mid.='$fields_'."['$tabkey']"."['".$fn."'] = ".'"'.$r['fieldname'].'";  ';
		if ($r['fieldtype']=='M') $size = - $r['length']; else $size = $r['length'];
		$mid.='$sizes_'."['$tabkey']"."['".$fn."'] = ".$size.';  ';
		if ($displaystyle!='horizontal'){
			if (($r['pane']!=$lastpane))	
				$mid.='$panebreak_'."['$tabkey']"."['".$fn."'] = ".'"'.$r['fieldname'].'";  ';
				$lastpane = $r['pane'];
			     $sec[$fn] = array( 'label' => $r['reportwriterheading'], 'size' => $r['length'], 'field' => $r['fieldname'] );
		} else // horizontal
		{
			foreach ($viewers as $viewer)
			if ($r[$viewer]) 
						$mid.='$viewer_'."['$viewer']"."['$tabkey']"."['".$fn."'] = ".'"'.$r['fieldname'].'";  ';
		}

		if ($once) {$mid.='$src_'."['$tabkey']"."= ".'"'.$r['ddtable'].'";  ';
		$once = false;
		}
	}
	if ($displaystyle!='horizontal') $metadata[$tabkey] = $sec; // close off next metadata area for json
	$bottom ="

";				

	echo linewrap($top).$mid.linewrap($bottom);
	mysql_free_result($result2);
}
mysql_free_result($result);


$result = dosql("Select distinct layout from viewerorder");
while ($r = mysql_fetch_object($result))
echo code($r->layout)."
//end of generated code for layout $r->layout
";
  $json = new Services_JSON();
  $jsonstuff_ =  $json->encode($metadata);

$jsonstuff_=<<<XXX
var fields = 
$jsonstuff_
XXX;
echo "//json database generated here:
\$jsonstuff_=<<<JSON
".$jsonstuff_."
JSON;
";
//that's about all
echo "
//end of generated code
?>";

?>