drop table ORDER_SERIES;
drop table DICOM_INSTANCE;
drop table SERIES;
drop table STUDY;
drop table MCORDER;
create table ORDER_SERIES (
   ORDER_SERIES_ID INTEGER not null generated always as identity,
   ORDER_SERIES_MCGUID VARCHAR(255),
   ORDER_SERIES_ORDERGUID VARCHAR(255),
   primary key (ORDER_SERIES_ID)
);
create table DICOM_INSTANCE (
   DINST_ID INTEGER not null generated always as identity,
   DINST_SERIES_ID BIGINT,
   DINST_LEVEL VARCHAR(255),
   DINST_SERIESINSTANCEUID VARCHAR(255),
   DINST_SOP_INSTANCE_UID VARCHAR(255),
   DINST_NFRAMES INTEGER,
   DINST_INSTANCE_NUMBER INTEGER,
   DINST_STUDY_INSTANCE_UID VARCHAR(255),
   DINST_REFERENCED_FILEID VARCHAR(255),
   DINST_WINDOW VARCHAR(255),
   primary key (DINST_ID)
);
create table SERIES (
   SERIES_ID INTEGER not null generated always as identity,
   SERIES_STUDY_ID BIGINT,
   SERIES_INSTANCE_UID VARCHAR(255),
   SERIES_MC_GUID VARCHAR(255),
   SERIES_TIME VARCHAR(255),
   SERIES_NUMBER INTEGER,
   SERIES_DATE VARCHAR(255),
   SERIES_MODALITY VARCHAR(255),
   SERIES_STUDY_INSTANCE_UID VARCHAR(255),
   SERIES_DESCRIPTION VARCHAR(255),
   SERIES_STATUS VARCHAR(255),
   SERIES_LAST_MODIFIED_TIME TIMESTAMP,
   primary key (SERIES_ID)
);
create table STUDY (
   STUDY_ID INTEGER not null generated always as identity,
   STUDY_PATIENT_ID VARCHAR(255),
   STUDY_INSTANCE_UID VARCHAR(255),
   STUDY_DATE VARCHAR(255),
   STUDY_DESCRIPTION VARCHAR(255),
   STUDY_PATIENT_NAME VARCHAR(255),
   STUDY_TIME VARCHAR(255),
   STUDY_MODALITY VARCHAR(255),
   primary key (STUDY_ID)
);
create table MCORDER (
   MCORDER_ID INTEGER not null generated always as identity,
   MCORDER_GUID VARCHAR(255),
   MCORDER_TRACKINGNUMBER VARCHAR(255),
   MCORDER_RECIPIENT_GUID VARCHAR(255),
   MCORDER_AFFILIATE VARCHAR(255),
   MCORDER_ORIGIN_GUID VARCHAR(255),
   MCORDER_DESCRIPTION VARCHAR(255),
   MCORDER_TIME_CREATED TIMESTAMP,
   MCORDER_PATIENT_NAME VARCHAR(255),
   MCORDER_PATIENT_ID VARCHAR(255),
   MCORDER_MODALITY VARCHAR(255),
   MCORDER_NSERIES INTEGER,
   MCORDER_NIMAGES INTEGER,
   MCORDER_PATIENT_DOB VARCHAR(255),
   MCORDER_PATIENT_SEX VARCHAR(255),
   MCORDER_PATIENT_AGE VARCHAR(255),
   primary key (MCORDER_ID)
);
alter table DICOM_INSTANCE add constraint FKC79096B8777C466E foreign key (DINST_SERIES_ID) references SERIES;
alter table SERIES add constraint FK9194F27793E52039 foreign key (SERIES_STUDY_ID) references STUDY;
commit;
