//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace gui_prototype.MedCommonsStudyService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StudyServiceSoapBinding", Namespace="http://medcommons.net:8080/jboss-net/services/StudyService")]
    public class StudyServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public StudyServiceService() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["gui-prototype.MedCommonsStudyService.StudyServiceService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://medcommons.net:8080/jboss-net/services/StudyService";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://study.services.central.medcommons.net", ResponseNamespace="http://medcommons.net:8080/jboss-net/services/StudyService")]
        [return: System.Xml.Serialization.SoapElementAttribute("selectStudyGuidsReturn")]
        public string[] selectStudyGuids(string selectionSpec) {
            object[] results = this.Invoke("selectStudyGuids", new object[] {
                        selectionSpec});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginselectStudyGuids(string selectionSpec, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("selectStudyGuids", new object[] {
                        selectionSpec}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndselectStudyGuids(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://study.services.central.medcommons.net", ResponseNamespace="http://medcommons.net:8080/jboss-net/services/StudyService")]
        [return: System.Xml.Serialization.SoapElementAttribute("retrieveStudyDataReturn")]
        public string retrieveStudyData(string studyGuid) {
            object[] results = this.Invoke("retrieveStudyData", new object[] {
                        studyGuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginretrieveStudyData(string studyGuid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("retrieveStudyData", new object[] {
                        studyGuid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndretrieveStudyData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
