/*
 * $Id: $
 * Created on Oct 10, 2004
 */
package net.medcommons.cxp;

/**
 * Indicates an exception generated by inappropriate
 * version of the CXP protocol (as determined by the CXPVersion or InformationSystem/Version
 * field).
 * 
 * @author sdoyle
 */
public class CXPVersionException extends CXPException {

  public CXPVersionException() {
    super();
  }
  /**
   * @param message
   */
  public CXPVersionException(String message) {
    super(message);
  }
  /**
   * @param message
   * @param cause
   */
  public CXPVersionException(String message, Throwable cause) {
    super(message, cause);
  }
  /**
   * @param cause
   */
  public CXPVersionException(Throwable cause) {
    super(cause);
  }
}
