//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace cxpsoap.CXPServer {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CXPServerSoapBinding", Namespace="http://gateway001.private.medcommons.net:9080/router/services/CXPServer")]
    public class CXPServerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public CXPServerService() {
            this.Url = "http://gateway001.private.medcommons.net:9080/router/services/CXPServer";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cxp.medcommons.net", ResponseNamespace="http://gateway001.private.medcommons.net:9080/router/services/CXPServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("putReturn")]
        public Response put(string ccrXml) {
            object[] results = this.Invoke("put", new object[] {
                        ccrXml});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginput(string ccrXml, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("put", new object[] {
                        ccrXml}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response Endput(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="put1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cxp.medcommons.net", ResponseNamespace="http://gateway001.private.medcommons.net:9080/router/services/CXPServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("putReturn")]
        public Response put(string ccrXml, string pin) {
            object[] results = this.Invoke("put1", new object[] {
                        ccrXml,
                        pin});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginput1(string ccrXml, string pin, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("put1", new object[] {
                        ccrXml,
                        pin}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response Endput1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cxp.medcommons.net", ResponseNamespace="http://gateway001.private.medcommons.net:9080/router/services/CXPServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("getReturn")]
        public string get(string xmlData) {
            object[] results = this.Invoke("get", new object[] {
                        xmlData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget(string xmlData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("get", new object[] {
                        xmlData}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endget(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="get1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cxp.medcommons.net", ResponseNamespace="http://gateway001.private.medcommons.net:9080/router/services/CXPServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("getReturn")]
        public string get(string trackingNumber, string pin) {
            object[] results = this.Invoke("get1", new object[] {
                        trackingNumber,
                        pin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget1(string trackingNumber, string pin, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("get1", new object[] {
                        trackingNumber,
                        pin}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endget1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://cxp.medcommons.net", ResponseNamespace="http://gateway001.private.medcommons.net:9080/router/services/CXPServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("getVersionReturn")]
        public string getVersion() {
            object[] results = this.Invoke("getVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetVersion(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getVersion", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetVersion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("Response", "urn:BeanService")]
    public class Response {
        
        /// <remarks/>
        public string opcode;
        
        /// <remarks/>
        public string pin;
        
        /// <remarks/>
        public string reason;
        
        /// <remarks/>
        public string response;
        
        /// <remarks/>
        public int status;
        
        /// <remarks/>
        public string trackingNumber;
        
        /// <remarks/>
        public string uid;
    }
}
